sudo: required

language: cpp
compiler:
- gcc
- clang

before_install:
- git checkout $TRAVIS_BRANCH

- if [ $(bii-support/travis/git/is_last_commit_travis.sh) = "true" ] ; then exit 0 ; fi
- bii-support/travis/git/configure.sh

install:
- bii-support/travis/install/all-headless.sh

- export TRAVIS_CXX=$CXX

script:
- bii-support/linux/build/default.sh

after_success:
- bii-support/travis/publish/biicode.sh

env:
  global:
  - USER_EMAIL=azriel91@gmail.com
  - USER_NAME="azriel"
  - BLOCK_NAME=sl_ax_game_object
  - BII_USER=azriel
  # Secure variables:
  # - BII_PASSWORD
  # - GITHUB_TOKEN
  - secure: "IAjviZq7EOej+2lHSeoovqZ8HCLi3FqNNN83LsiuZfsW8UXtcPJdiVnuTDQA5gB7k2J3O9uDSP+l146GR+ITkjXIPyNIKRNaUtTdZBmDtroWEgW2c35hQtDE+pGqLiMLesiEgNP2r307B1JovSQdcD26rbsZxDbxM37z5mGtr6XRNHiHpzROZoGfjRnfkXjrP3X+t/QOXW/kC8Dh1bt38g/PekxE2tSiEzQuNpN+ptC9TgnADlXEKh8Ohaaq0zYgy2U1Sh898cBg5xCVtTcIypDpTyteR0cXYL+s3lUrPYGjBGLHOJOgGAwBNqqWK2GcqEt9yCkQvTJogQ2T9s4MpfAhCLABaCNKm2YmD5mqhIEPTxrQBeGZlo459x9/XLsUP67nE5VeKYGlidaF0TO5wljheoBhCDNs/kgEJn8uJWiur0VmQl3/NMJ8TvbAALR/I6C1GU0Uf2aVNNg+ixC+jSkkqU4J+8ypkhmmc4u5kcJVMdSZM4QmbHtS07eTrCh5oWWw5qdzVmHOSnV4RJHQegJVPDz88eLfo0i1/mP5VSaXIo9TdgYP1aO+SpztFgvbRf6waR3wiU4+h0e2l6MWHN0MOVqY9gFh3ZAr5ugxF1c5jRN6xoSfod0XaSO92sd+JjEVsD/pm3MR/zZpWV6u8mkjjI53szi4RVjHR2QG6VA="
  matrix:
  - BUILD_SHARED_LIBS=OFF
  - BUILD_SHARED_LIBS=ON